sudo: required

language: go

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_842b00123408_key -iv $encrypted_842b00123408_iv -in id_rsa.enc -out docker/pro/.ssh/id_rsa -d

script:
- cd docker/pro
- ./build.sh