sudo: required

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_842b00123408_key -iv $encrypted_842b00123408_iv -in id_rsa.enc -out docker/pro/.ssh/id_rsa -d
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
- cd docker/pro
- ./build.sh