version: '3'
services:
  api:
    image: liv1020/move-car-api:pro
    volumes:
          - ./conf:/usr/local/server/conf
    links:
      - db
    ports:
      - 8080:8080
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ../../data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: application
      MYSQL_USER: application
      MYSQL_PASSWORD: 123456
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']