mode: debug
port: 8080
db:
  host: localhost
  port: 3306
  user: application
  password: 123456
  database: application
  charset: utf8mb4
  maxidle: 10
  maxopen: 20
wechat:
  appid: wx351aab24bd75e0ab
  appsecret: fe53187244f178a7a4ee817599107e00
  templateid: 8Z_lm_wAhACXyFuSXqLP89tAfl0wBiYbvur9wM12Sew
  confirmurl: http://mc.liv1020.com/confirm
  token: 244f178a7a4ee81
  encodingaeskey: 8fwF7eV4J2kaC57ZDWYq9oiD35aM4ZYGdO3GR0chhxq
aliyun:
  accesskeyid: LTAIQk3xt3OM3qIv
  accesskeysecret: u57Niqa807wkxiXBNOP8Vkk9CbzmBX
  vms:
    calledshownumber: 09314267618
    ttscode: TTS_138069424
  sms:
    signname: 智捷挪车
    templatecode: SMS_137875084