port: 8080
mode: debug
db:
  host: localhost
  port: 3306
  user: application
  password: 123456
  database: application
  charset: utf8mb4
  maxidle: 10
  maxopen: 20
wechat:
  appid: wx351aab24bd75e0ab
  appsecret: fe53187244f178a7a4ee817599107e00
  oauthurl: http://mc.liv1020.com/oauth/code
  templateid: xxxxxxx
  confirmurl: xxxxxxx
aliyun:
  accesskeyid: LTAIQk3xt3OM3qIv
  accesskeysecret: u57Niqa807wkxiXBNOP8Vkk9CbzmBX
  vms:
    signname: 智捷挪车
    templatecode: SMS_137875084