version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ../data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: application
      MYSQL_USER: application
      MYSQL_PASSWORD: 123456